const bodyRegions=[{key:"head",name:"頭頸部",adult:.1,child:.2,pasi:.1},{key:"upper",name:"上肢",adult:.2,child:.2,pasi:.2},{key:"trunk",name:"体幹",adult:.3,child:.3,pasi:.3},{key:"lower",name:"下肢",adult:.4,child:.3,pasi:.4}];
const areaOptions=[{value:0,label:"0",sub:"0%"},{value:1,label:"1",sub:"1–9%"},{value:2,label:"2",sub:"10–29%"},{value:3,label:"3",sub:"30–49%"},{value:4,label:"4",sub:"50–69%"},{value:5,label:"5",sub:"70–89%"},{value:6,label:"6",sub:"90–100%"}];
const easiSeverity=[{value:0,label:"0",sub:"なし"},{value:1,label:"1",sub:"軽度"},{value:1.5,label:"1.5",sub:"軽～中"},{value:2,label:"2",sub:"中等度"},{value:2.5,label:"2.5",sub:"中～高度"},{value:3,label:"3",sub:"高度"}];
const pasiSeverity=[{value:0,label:"0",sub:"なし"},{value:1,label:"1",sub:"軽度"},{value:2,label:"2",sub:"中等度"},{value:3,label:"3",sub:"高度"},{value:4,label:"4",sub:"極めて高度"}];
const EASI_SIGNS=[["erythema","紅斑"],["papulation","浮腫／丘疹"],["excoriation","掻破痕"],["lichenification","苔癬化"]];
const PASI_SIGNS=[["erythema","紅斑"],["induration","肥厚／浸潤"],["scaling","鱗屑"]];
const easiState={},pasiState={};
function ensure(obj,key,signs){if(!obj[key]){obj[key]={area:0};signs.forEach(([s])=>obj[key][s]=0)}}
function optionButton(o,cls,onClick,selected){const b=document.createElement("button");b.type="button";b.className=`option-btn ${cls} ${selected?"selected":""}`;b.innerHTML=`${o.label}<small style="display:block;font-size:.68em;line-height:1.1">${o.sub}</small>`;b.dataset.value=o.value;b.addEventListener("click",onClick);return b}
function addOptions(card,label,options,stateKey,group,onChange){const block=document.createElement("div");block.className="field-block";const l=document.createElement("div");l.className="field-label";l.textContent=label;block.appendChild(l);const g=document.createElement("div");g.className=`option-grid ${group==="area"?"":group}`;g.dataset.group=stateKey;options.forEach(o=>g.appendChild(optionButton(o,group,()=>onChange(o.value),o.value===0)));block.appendChild(g);card.appendChild(block)}
function refresh(card,group,value){const g=card.querySelector(`.option-grid[data-group="${group}"]`);if(!g)return;g.querySelectorAll(".option-btn").forEach(b=>b.classList.toggle("selected",Number(b.dataset.value)===Number(value)))}
function renderEasi(){const w=document.getElementById("easi-regions");w.innerHTML="";bodyRegions.forEach(r=>{ensure(easiState,r.key,EASI_SIGNS);const c=document.createElement("div");c.className="region-card";c.innerHTML=`<div class="region-head"><h3>${r.name}</h3><div class="region-score">部位スコア：<span id="easi-${r.key}-score">0.0</span></div></div>`;addOptions(c,"面積スコア",areaOptions,"area","area",v=>{easiState[r.key].area=v;calcEasi();refresh(c,"area",v)});EASI_SIGNS.forEach(([s,l])=>addOptions(c,l,easiSeverity,s,"severity",v=>{easiState[r.key][s]=v;calcEasi();refresh(c,s,v)}));w.appendChild(c)})}
function renderPasi(){const w=document.getElementById("pasi-regions");w.innerHTML="";bodyRegions.forEach(r=>{ensure(pasiState,r.key,PASI_SIGNS);const c=document.createElement("div");c.className="region-card";c.innerHTML=`<div class="region-head"><h3>${r.name}</h3><div class="region-score">部位スコア：<span id="pasi-${r.key}-score">0.0</span></div></div>`;addOptions(c,"面積スコア",areaOptions,"area","area",v=>{pasiState[r.key].area=v;calcPasi();refresh(c,"area",v)});PASI_SIGNS.forEach(([s,l])=>addOptions(c,l,pasiSeverity,s,"pasi-severity",v=>{pasiState[r.key][s]=v;calcPasi();refresh(c,s,v)}));w.appendChild(c)})}
function calcEasi(){const raw=document.getElementById("easi-age").value;const age=Number(raw);const valid=raw!==""&&Number.isFinite(age)&&age>=0&&age<=120;let total=0;bodyRegions.forEach(r=>{ensure(easiState,r.key,EASI_SIGNS);const s=easiState[r.key],coef=valid&&age<8?r.child:r.adult,sum=EASI_SIGNS.reduce((a,[k])=>a+Number(s[k]),0);s._score=sum*Number(s.area)*coef;total+=s._score;document.getElementById(`easi-${r.key}-score`).textContent=s._score.toFixed(1)});document.getElementById("easi-total").textContent=total.toFixed(1);document.getElementById("easi-bottom-total").textContent=total.toFixed(1);const n=document.getElementById("easi-type"),an=document.getElementById("easi-age-note");if(!valid){n.textContent="年齢未入力";an.textContent="年齢を入力すると係数を自動選択します。"}else if(age<8){n.textContent="8歳未満：小児係数を使用";an.textContent="0～7歳：頭頸部0.2、上肢0.2、体幹0.3、下肢0.3"}else{n.textContent="8歳以上：8歳以上係数を使用";an.textContent="8歳以上：頭頸部0.1、上肢0.2、体幹0.3、下肢0.4"}}
function calcPasi(){let total=0;bodyRegions.forEach(r=>{ensure(pasiState,r.key,PASI_SIGNS);const s=pasiState[r.key],sum=PASI_SIGNS.reduce((a,[k])=>a+Number(s[k]),0);s._score=sum*Number(s.area)*r.pasi;total+=s._score;document.getElementById(`pasi-${r.key}-score`).textContent=s._score.toFixed(1)});document.getElementById("pasi-total").textContent=total.toFixed(1);document.getElementById("pasi-bottom-total").textContent=total.toFixed(1)}
async function copyText(t){try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement("textarea");a.value=t;document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}const e=document.getElementById("copy-status");e.textContent="結果をコピーしました。";clearTimeout(window.copyTimer);window.copyTimer=setTimeout(()=>e.textContent="",2000)}
function easiText(){let t=`EASI：${document.getElementById("easi-total").textContent} / 72`;const a=document.getElementById("easi-age").value.trim();if(a)t+=`\n年齢：${a}歳`;bodyRegions.forEach(r=>{ensure(easiState,r.key,EASI_SIGNS);t+=`\n${r.name}：${easiState[r.key]._score.toFixed(1)}`});return t}
function pasiText(){let t=`PASI：${document.getElementById("pasi-total").textContent} / 72`;bodyRegions.forEach(r=>{ensure(pasiState,r.key,PASI_SIGNS);t+=`\n${r.name}：${pasiState[r.key]._score.toFixed(1)}`});return t}
function resetState(obj,signs){Object.keys(obj).forEach(k=>delete obj[k]);bodyRegions.forEach(r=>{obj[r.key]={area:0};signs.forEach(([s])=>obj[r.key][s]=0)})}
document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active-panel"));t.classList.add("active");document.getElementById(t.dataset.target).classList.add("active-panel")}));
renderEasi();renderPasi();calcEasi();calcPasi();document.getElementById("easi-age").addEventListener("input",calcEasi);document.getElementById("easi-copy").addEventListener("click",()=>copyText(easiText()));document.getElementById("pasi-copy").addEventListener("click",()=>copyText(pasiText()));document.getElementById("easi-reset").addEventListener("click",()=>{resetState(easiState,EASI_SIGNS);document.getElementById("easi-age").value="";renderEasi();calcEasi()});document.getElementById("pasi-reset").addEventListener("click",()=>{resetState(pasiState,PASI_SIGNS);renderPasi();calcPasi()});
